apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oxigraph-cloud.fullname" . }}-config
  labels:
    {{- include "oxigraph-cloud.labels" . | nindent 4 }}
data:
  BACKEND: {{ .Values.backend.type | quote }}
  PD_ENDPOINTS: {{ .Values.backend.tikv.pdEndpoints | quote }}
  SHACL_MODE: {{ .Values.shacl.mode | quote }}
  BIND: {{ .Values.server.bind | quote }}
  QUERY_TIMEOUT: {{ .Values.server.queryTimeout | quote }}
  CORS_ORIGINS: {{ .Values.server.corsOrigins | quote }}
