{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "oxigraph-cloud.fullname" . }}
  labels:
    {{- include "oxigraph-cloud.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "oxigraph-cloud.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
{{- end }}
